apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/mumubin/jx-learn:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/mumubin/jx-learn:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: jx-learn
        chartPath: charts/jx-learn
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/mumubin/jx-learn'
          image.tag: '{{.DIGEST_HEX}}'
